server:
  port: 8001
  servlet:
    context-path: /employee

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:  org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform:  org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: employee-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9010/eureka/
  instance:
    # 使用IP地址注册
    prefer-ip-address: true
    # 向注册中心注册服务id
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 发送心跳间隔
    lease-renewal-interval-in-seconds: 5
    # 续约到期时间
    lease-expiration-duration-in-seconds: 10
logging:
  level:
    root: debug

dept-service:
  ribbon:
    # 请求连接的超时时间
    ConnectTimeOut: 250
    # 请求处理的超时时间
    ReadTimeOut: 1000
    # 对所有操作请求都进行重试
    OkToRetryOnAllOperations: true
    # 切换实例的重试次数
    MaxAutoRetriesNextServer: 2
    # 对当前实例的重试次数
    MaxAutoRetries: 1
