server:
  port: 8000
  servlet:
    context-path: /dept

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:  org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform:  org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: dept-service
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:9000/eureka/,http://localhost:9010/eureka/
  instance:
    # 使用IP地址注册
    prefer-ip-address: true
    # 向注册中心注册服务id
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 发送心跳间隔
    lease-renewal-interval-in-seconds: 5
    # 续约到期时间
    lease-expiration-duration-in-seconds: 10



