server:
  port: 7060
spring:
  application:
    name: apollo-client
apollo:
  client:
    name: test
  bootstrap:
    enabled:  true  #开启Apollo
  meta: http://192.168.0.111:8080
app:
  id: client-test #指定Apollo配置中心中的appid