server:
  port: 7090

spring:
  application:
      name: stream-producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          auto-create-topics: true
      bindings:
        output:
          destination: kafka-stream #指定消息的目的地
          content-type: text/plain
          producer:
            partition-key-expression: payload.id #分区关键字  对象中的id
            partition-key: 2 # 分区数量
      binders:  #配置绑定器
        defaultRabbit:
          type: kafka

