server:
  port: 7090

spring:
  application:
      name: stream-producer
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: rabbit-stream #指定消息的目的地，在rabbitmq中发送到一个rabbit-stream的exchange
          producer:
            partition-key-expression: payload #分区关键字  对象中的id
            partition-key: 2 # 分区大小
      binders:  #配置绑定器
        defaultRabbit:
          type: rabbit
