server:
  port: 7091

spring:
  application:
      name: stream-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          auto-create-topics: true
      bindings:
        input:  #内置的获取消息的通道，
          destination: kafka-stream
          group: group1 #设置消息的组名称(同名组中有多个消费者，只会有一个去消费消息)
          consumer:
            partitioned: true # 开启分区支持
      binders:  #配置绑定器
        defaultRabbit:
          type: kafka
      instance-count: 2 #消费者总数
      instance-index: 0 #当前消费者的索引 另外一个1
