server:
  port: 8061
spring:
  application:
    name: sleuth-product
    # 配置consul的服务注册
    consul:
      host: 127.0.0.1 # consul服务器主机地址
      port: 8500  # consul服务器ip地址
      discovery:
        # 是否需要注册
        register: true
        # 注册的实例ID 唯一标志
        instance-id:  ${spring.application.name}:${server.port}
        # 服务名称
        service-name: ${spring.application.name}
        # 服务请求端口
        port: ${server.port}
        # 指定开启ip地址注册
        prefer-ip-address: true
        # 当前服务的请求ip
        ip-address: ${spring.cloud.client.ip-address}
  zipkin:
    base-url: http://127.0.0.1:9411/ # server的请求路径
    sender:
      type: web	# 三种方式 rabbit、kafka、web
  sleuth:
    sampler:
      probability: 1 # 采样比

# 配置Sleuth
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
