server:
  port: 8031

# 在Feign模块中要生效sentinel的超时时间，必须设置此时间
#
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000



spring:
  application:
      name: sentinel-order
  cloud:
    sentinel:
      datasource:
        ds1:
          file:
            file: classpath:flowrule.json
            data-type: json
            rule-type: degrade
      transport:
        dashboard: localhost:8090 #sentinel控制台的请求地址
      eager: true # 立即加载,取消sentinel控制台软加载
    # 配置consul的服务注册
    consul:
      host: 127.0.0.1 # consul服务器主机地址
      port: 8500  # consul服务器ip地址
      discovery:
        # 是否需要注册
        register: true
        # 注册的实例ID 唯一标志
        instance-id:  ${spring.application.name}:${server.port}
        # 服务名称
        service-name: ${spring.application.name}
        # 服务请求端口
        port: ${server.port}
        # 指定开启ip地址注册
        prefer-ip-address: true
        # 当前服务的请求ip
        ip-address: ${spring.cloud.client.ip-address}
feign:
  sentinel:
    enabled: true
