server:
  port: 8021

spring:
  application:
      name: consul-order
  cloud:
    # 配置consul的服务注册
    consul:
      host: 127.0.0.1 # consul服务器主机地址
      port: 8500  # consul服务器ip地址
      discovery:
        # 是否需要注册
        register: true
        # 注册的实例ID 唯一标志
        instance-id:  ${spring.application.name}:${server.port}
        # 服务名称
        service-name: ${spring.application.name}
        # 服务请求端口
        port: ${server.port}
        # 指定开启ip地址注册
        prefer-ip-address: true
        # 当前服务的请求ip
        ip-address: ${spring.cloud.client.ip-address}

# 配置Feign日志输出 NONE(默认) - BASIC - HEADERS - FULL
feign:
  client:
    config:
      consul-product: # 需要调用的服务名
        loggerLevel:  FULL
  # 作用:开启对hystrix的使用
  hystrix:
    enabled: true

logging:
  level:
    com.learn.consul.order.feign.ProductFeignClient: debug

# 在Feign模块中要生效hystrix的超时时间，必须设置此时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: ExecutionIsolationStrategy.SEMAPHORE # 信号量隔离 - THREAD 线程池隔离
          thread:
            timeoutInMilliseconds: 3000 #默认的连接超时时间1秒，若1秒内没有返回数据，则触发降级方法
      circuitBreaker:
        requestVolumeThreshold: 5 #触发熔断最小请求次数 默认值20.意思是至少有20个请求才进行errorThresholdPercentage错误百分比计算
        sleepWindowInMilliseconds: 10000 #半开试探休眠时间，默认值5000ms。当熔断器开启一段时间之后比如5000ms，会尝试放过去一部分流量进行试探，确定依赖服务是否恢复。
        errorThresholdPercentage: 50 #设定错误百分比，默认值50%，例如一段时间（10s）内有100个请求，其中有55个超时或者异常返回了，那么这段时间内的错误百分比是55%，大于了默认值50%，这种情况下触发熔断器-打开。


management:
  endpoints:
    web:
      exposure:
        include: '*'